[package]
name = "kannweg_3d"
version = "0.1.0"
authors = ["itmuckel <michael.bachner@outlook.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rg3d = { path = "../rg3d" }
rand = "0.7.3"
num = "0.3.0"

[profile.dev.package."*"]
opt-level = 3
